### ISSUE TITLE
Rename module

### ISSUE THREAD

**Issue by andrewgsavage** [hgrecco/pint-pandas#1]
Running import pint-pandas doesn't work. Seems hyphens aren't recommended in module names. Can the module be renamed to pintpandas or similiar?

**Comment by andrewgsavage** [comment]
Cool, thanks for the examples

**Comment by hgrecco** [comment]
I have changed the internal package name from `pintpandas` to `pint_pandas` as I think it will make easier to read future extensions (e.g. `pint_dask`, etc). I still need to fix the import in Pint
