### ISSUE TITLE
Unit Conversions based on updated registry

### ISSUE THREAD

**Issue by caerus-data** [hgrecco/pint-pandas#10]
I've updated the registry with a new quantity 

`Q_ = ureg.Quantity`
`ureg.define('sacks = 94 * pounds = sack')`

[WORKS FINE]
`lbs = Q_(94, 'pounds')`

`print(lbs.to('sacks'))`

[WORKS]

`yy=Q_(0.000961390592872627,'m**3/kg')`

`yy.to('ft**3/sack')`

[Doesn't Work]
[This part works]
`df=pd.DataFrame({'test':pd.Series([0.000961390592872627], dtype="pint[m**3/kg]")})`

[DOESN'T WORK]
`df['test'][0].to('ft**3/sacks')`

UndefinedUnitError: 'sacks' is not defined in the unit registry

**Comment by hgrecco** [comment]
(I have moved this issue from pint). 

The offending line is [here](https://github.com/hgrecco/pint-pandas/blob/master/pintpandas/pint_array.py#L48).

You can monkey patch it by assigning
```python
PintType.ureg = ureg
```
(where ureg is your registry)

However, I think we need to provide a better solution. I think that the best way would be to use the Application Registry

**Comment by caerus-data** [comment]
Worked great! Thanks! - Resolved
