### ISSUE TITLE
pint_pandas.quantify tries to parse columns without unit 

### ISSUE THREAD

**Issue by wakass** [hgrecco/pint-pandas#119]
pint_pandas' quantify function currently is not able to convert only part of the columns that are in the dataframe. It would be convenient to be able to do this, since any other columns contribute greatly to the easy of use of pandas: E.g. groupby, etc.

Any other option to solve this problem, adding some robustness here (leaving unconvertible columns intact), could ofcourse also work.

This seems related to issue #46 

`C:\Python39\lib\site-packages\pint_pandas\pint_array.py:194: RuntimeWarning: pint-pandas does not support magnitudes of <class 'str'>. Converting magnitudes to float.`

**Comment by andrewgsavage** [comment]
closed by #132
