### ISSUE TITLE
Experimental status?

### ISSUE THREAD

**Issue by deeplook** [hgrecco/pint-pandas#120]
I'm just curious what would be needed for this repo to drop the "experimental" status attached to it? ;)

**Comment by arkanoid87** [comment]
find all critical bugs, for example
https://github.com/hgrecco/pint-pandas/issues/122

**Comment by andrewgsavage** [comment]
There are a number of things that can't work because of how pandas detects whether something is a scalar or iterable.

This was the last progress I'm aware of made on it:
https://github.com/pandas-dev/pandas/pull/44626

**Comment by deeplook** [comment]
I was asking because to me it seems like pandas support in this repo is still too brittle to be really usable in practice, and OTOH there is [pint-xarray](https://github.com/xarray-contrib/pint-xarray) which _seems_ to be more ahead in comparison (haven't really tested it yet), so maybe there is something to adopt from there. But again, this is all based on some speculation.
