### ISSUE TITLE
Compatibility with 'uncertainties'?

### ISSUE THREAD

**Issue by Cs137** [hgrecco/pint-pandas#124]
Many thanks for your work on this package and especially for `pint` itself! It makes life much easier, and in order to make life more easy, I would like to request a feature.

In my opinion the usage of the "pint" dtype for a column containing an `uarray` would be very handy, but there seems to be an issue with the `__init__` method of `PintArray`. If I get it correctly, it  creates a `np.array` from the provided data and thus wants to convert the `uarray` into floats, which causes the following error (*I shortened the path and inserted [...]*):

```python
File [...]/python3.10/site-packages/pint_pandas/pint_array.py:198, in PintArray.__init__(self, values, dtype, copy)
    193     data_dtype = next(x for x in values if not isinstance(x, float))
    194     warnings.warn(
    195         f"pint-pandas does not support magnitudes of {type(data_dtype)}. Converting magnitudes to float.",
    196         category=RuntimeWarning,
    197     )
--> 198 self._data = np.array(values, float, copy=copy)
    199 self._Q = self.dtype.ureg.Quantity

File [...]/python3.10/site-packages/uncertainties/core.py:2712, in add_operators_to_AffineScalarFunc.<locals>.raise_error(self)
   2711 def raise_error(self):
-> 2712     raise TypeError("can't convert an affine function (%s)"
   2713                     ' to %s; use x.nominal_value'
   2714                     # In case AffineScalarFunc is sub-classed:
   2715                     % (self.__class__, coercion_type))

TypeError: can't convert an affine function (<class 'uncertainties.core.Variable'>) to float; use x.nominal_value
```

Here some snippets to reproduce the case:
```python
import pandas as pd
import pint
import pint_pandas
from uncertainties import ufloat_fromstr, unumpy

data = {'a': {0: 0.01, 1: 0.28, 2: 0.33, 3: 0.78}, 
        'b': {0: '0.79+/-0.08', 1: '0.340+/-0.030', 
              2: '0.52+/-0.05', 3: '0.250+/-0.020'}}

df = pd.DataFrame(data)
df.b = [ufloat_fromstr(x) for x in df.b]

# dtype assignment works fine for float column
df.a = df.a.astype('pint[g]')

# dtype assignment to ufloat column causes the issue
df.b = df.b.astype('pint[g]')
```

```python
# uarray creation before dtype assignment leads to same issue
n = [x.n for x in df.b]
s = [x.s for x in df.b]
ua = unumpy.uarray(n, s)

df.b = pd.Series(ua, dtype='pint[g]')
```

```python
# and the usage of the PintArray constructor directly as well (as expected)
df.b = pint_pandas.PintArray(ua, 'g')
```

A compatibility between `PintArray` and `uncertainties`, as fulfilled by the `Measurement` class in `pint` would in my opinion be a huge improvement in `pint-pandas`.

**Comment by andrewgsavage** [comment]
Yes, this would be nice.

@hgrecco has been wanting to separate out Measurement from pint, which might mean you want a separate package for uncertainties with pandas. Probably worth waiting till that's done too - although that's been on the agenda for a while now.

**Comment by MichaelTiemannOSC** [comment]
xref: https://github.com/hgrecco/pint-pandas/pull/140

**Comment by andrewgsavage** [comment]
closing this as it's now possible with UncertaintyArray
https://pint-pandas.readthedocs.io/en/latest/user/initializing.html

**Comment by Cs137** [comment]
Since I still miss the possibility to write a `DataFrame` with "pint uncertainty series" into a file and restore it later on, I wrote [`Series`/`DataFrame` accessors](https://codeberg.org/Cs137/unpaac) that allow to (de)convolute such series. The accessors can be used to restore a `DataFrame` with uncertainties and units [as described here](https://codeberg.org/Cs137/unpaac#save-a-dataframe-to-csv-and-restore-dataframe-from-csv).

**Comment by Cs137** [comment]
> some (maybe all?) of those accessors could be added to uncertainties-pandas / pint-pandas

I thought about this as well, but since it requires both, pint-pandas and uncertainty-pandas, it does not really fit into one of them. But I'd be happy to hear your thoughts, @andrewgsavage, in case you disagree.

Cheers,
Christian

**Comment by andrewgsavage** [comment]
There should be accessors for .n, .s for uncertainties-pandas that operate on floats, without units.

I am less sure on whether the pint+uncertainties accessors should be in pint-pandas or elsewhere. I think hgrecco mentioned splitting measurements outside of pint but that was a while ago. What you have is fine for now, we can see how well this works for people - which will need adding links to docs so they can find it!
