### ISSUE TITLE
Pint-pandas having its own UnitRegistry()

### ISSUE THREAD

**Issue by sigvaldm** [hgrecco/pint-pandas#14]
Dear all,

As of today, `PintType` has its own `UnitRegistry()`, which of course is incompatible with other registries. I.e.:

```
df = pd.read_csv('dummy.csv', header=[0,1])
df = df.pint.quantify()

ureg = pint.UnitRegistry()
uregi = df.A.dtype.ureg

df.A+3*ureg.s # fails
df.A+3*uregi.s # works
```

Since it is possible elsewhere in Pint to have custom registries, it seems more consistent to also allow this in pint-pandas. Would it be possible, for instance, to let `df.pint.quantify()` take an optional `ureg` argument? I may contribute when/if I find time (for me this is only recreational programming).

**Comment by andrewgsavage** [comment]
It is possible to change the ureg to another, see the advanced example at the end of

notebooks/pandas_support.ipynb

Is that what you're referring to?

**Comment by sigvaldm** [comment]
Yes, this is indeed what I was looking for. I didn't notice this. But I suppose it still means you can only have one unit registry for all Pandas dataframes? Unlike in pure Pint where you can have several (incompatible) unit registries for different variables. Not that I think it matters. At least for me it doesn't.

**Comment by andrewgsavage** [comment]
Correct, one registry. This is necessary to allow pint['m'] as a dtype, which I think is worth the cost of not supporting multiple registries.

**Comment by sigvaldm** [comment]
Right, thanks. As long as there's no actual need for multiple registries, I agree it's not worth the effort.
