### ISSUE TITLE
on import ModuleNotFoundError: No module named 'pint.quantity'

### ISSUE THREAD

**Issue by RobbesU** [hgrecco/pint-pandas#153]
I cannot even get pint-pandas to import, giving above error about missing 'pint.quantity'.  Am I missing something, possibly a version conflict? All packages are installed via Anaconda,  and all latest as checked via `conda update --all`  
Verions: python = 3.9.13 , pandas = 1.4.4 , pint = 0.20.1, pint-pandas = 0.2

```
import pandas as pd
import pint
import pint_pandas
```

Error appears to originate from pint_arry.py
```
~\anaconda3\lib\site-packages\pint_pandas\pint_array.py in <module>
     19 from pandas.core.indexers import check_array_indexer
     20 from pint import compat, errors
---> 21 from pint.quantity import _Quantity
     22 from pint.unit import _Unit
     23 

ModuleNotFoundError: No module named 'pint.quantity'
```

I note Anaconda version pint-pandas = 0.2, whilst here on GH seems to be 0.3?

**Comment by andrewgsavage** [comment]
0.3 has been released now and this works again
