### ISSUE TITLE
doc link to pint-pandas jupyter notebook broken

### ISSUE THREAD

**Issue by RobbesU** [hgrecco/pint-pandas#154]
The link in  `pint-pandas jupyter notebook` under Pandas Integration in the docs, going to https://github.com/hgrecco/pint-pandas/blob/master/notebooks/pandas_support.ipynb  via the results in a '404 page not found'

**Comment by andrewgsavage** [comment]
Do you have the url where you found that link?

**Comment by RobbesU** [comment]
Oh, whoops, sorry @andrewgsavage . It's a _pint_ issue, not pint-pandas.  `https://github.com/hgrecco/pint` near the bottom.   i'd been flicking back and forth between the two so much trying to figure out the import failure. Wrong library, albeit same author ;-).  i'll repost to pint's GH issues.
