### ISSUE TITLE
Pint 0.21 broke pint_pandas initialization

### ISSUE THREAD

**Issue by vasilisniaouris** [hgrecco/pint-pandas#175]
Hello,

I just upgraded to pint 0.21 and the command `import pint_pandas` returns the following error:

```pycon
Traceback (most recent call last):
   ...
AttributeError:` module 'pint.compat' has no attribute 'upcast_types'. Did you mean: 'is_upcast_type'?
```

Seems like line 994 of pint_array (`compat.upcast_types.append(PintArray)`) is the issue.

**Comment by andrewgsavage** [comment]
fixed by #171
