### ISSUE TITLE
support for pandas v0.25.0

### ISSUE THREAD

**Issue by sunt05** [hgrecco/pint-pandas#20]
this version doesn't work with `pandas v0.25.0`.

**Comment by andrewgsavage** [comment]
For the most part this version will work:
https://github.com/andrewgsavage/pint-pandas/tree/plotting

But there are some tests/fixtures that need adding to fully satisfy pandas' api, see the 0.25 tests here:
https://travis-ci.org/hgrecco/pint-pandas/builds/573360779

**Comment by johnbomidi** [comment]
So, is this why I was facing an issue? 

https://github.com/hgrecco/pint/issues/779#issuecomment-536080167

**Comment by andrewgsavage** [comment]
yes, use https://github.com/andrewgsavage/pint-pandas/tree/plotting till it's merged.

**Comment by romor001** [comment]
Any estimate on when the branch from andrewgsavage is going to get merged?

**Comment by andrewgsavage** [comment]
has been merged and works with pandas 1.2
