### ISSUE TITLE
Constructor path unexpectedly changes outcome

### ISSUE THREAD

**Issue by rwijtvliet** [hgrecco/pint-pandas#205]
## Example

```python
import pandas as pd
import pint
import pint_pandas
import numpy as np
units1 = pd.Series([3.0, np.nan]).astype('pint[MWh]')
units2 = pd.Series([3.0, np.nan], dtype='pint[MWh]')
units3 = pd.Series([3, np.nan], dtype='pint[MWh]')
```

## Inconsistency 1: representation of `NaN`.

The value of the `NaN` element at index position 1 changes slightly between `1` and `2`/`3`:

```python
>>> units1[1]
<Quantity(nan, 'megawatt_hour')>
>>> units2[1]
<Quantity(<NA>, 'megawatt_hour')>
>>> units3[1]
<Quantity(<NA>, 'megawatt_hour')>

>>> type(units1[1].m)
<class 'numpy.float64'>
>>> type(units2[1].m)
<class 'pandas._libs.missing.NAType'>
```

## Inconsistency 2: impact of `int`

Also, getting the magnitude delivers inconsistent results. Surprisingly, the difference here is between `1`/`2` and `3`:

```python
>>> units1.pint.m
0    3.0
1    NaN
dtype: float64
>>> units2.pint.m
0    3.0
1    NaN
dtype: float64
>>> units3.pint.m
0       3
1    <NA>
dtype: object
```

Notice how the latter is a series of objects.

## Versions

Tested with following versions of (pandas, pint, pint-pandas):

* (1.5.3, 0.22, 0.4)

* (1.5.3, 0.22, 0.5)

* (2.1.0, 0.22, 0.5)

All give the same result

**Comment by andrewgsavage** [comment]
you're seeing the effects of the underlying data stored in different ways. you can view this with 
`no_units3.values.data`
This happens as the data is passed through `pd.array` in `__init__`. This ensures the data array can store a form of nan.

If I'm understanding correctly, you're expecting all these to behave the same. Previously the data was converted to float so ints and other types could not be stored, but prevented these issues. However people wanted to store other dtypes.

including the data array dtype, eg 'dtype: pint[m][int]' would help with these issues (at least make it clearer as to why its behaving odd), but hasn't been as necessary so far.

**Comment by andrewgsavage** [comment]
fixed by https://github.com/hgrecco/pint-pandas/pull/247
