### ISSUE TITLE
Add Unary Operator Support to PintArrays

### ISSUE THREAD

**Issue by Nick-Hemenway** [hgrecco/pint-pandas#221]
Currently the below example does not work:

```python
from pint_pandas import PintArray

p = PintArray(np.array([1,2,3], dtype=np.float64), 'm')
p1 = -p
```

Instead you must multiply by a negative scalar as follows:
```python
p1 = -1*p
```

**Comment by andrewgsavage** [comment]
I had hoped to get this working with #160 

Alternatively `PintArray.__pos__` and `PintArray.__neg__` could be implemented for  `-p`   and `-p` .
The unary tests in #160 can be copied.
