### ISSUE TITLE
Broken string representation

### ISSUE THREAD

**Issue by mflova** [hgrecco/pint-pandas#229]
I am not sure if this is more on the `pint` side about how the pint array is represented or if it belongs to `pint-pandas`, but I consider this to be a critical problem as the representation is totally missleading and wrong:

```py
df = pd.DataFrame({"a": [1,2,3], "b": [1,2,3]})
print(df)
"""
   a  b
0  1  1
1  2  2
2  3  3
"""
df = df.astype("pint[rpm]")
print(df)
"""
0
1  a  b
2  1  1
"""
```

This problem seems to be present whenever a `pint` data (with multiple values) needs to be displayed. Therefore, printing after an aggregation based method is performed is also broken. I also tested with `MultiIndex` in both index and columns and also broken

**Comment by andrewgsavage** [comment]
what versions are you using? tis works fine for me
```python
pint_pandas.show_versions()
```

    {'numpy': '1.25.2',
     'pandas': '2.1.0',
     'pint': '0.23',
     'pint_pandas': '0.6.dev6+g2e087e6'}
    


```python
df = pd.DataFrame({"a": [1,2,3], "b": [1,2,3]})
print(df)
```

       a  b
    0  1  1
    1  2  2
    2  3  3
    


```python
df = df.astype("pint[rpm]")
print(df)
```

       a  b
    0  1  1
    1  2  2
    2  3  3

**Comment by mflova** [comment]
I apologize, it seems I was using some outdated versions I should have checked. It is fixed now. I will start using the tool. Thanks!
