### ISSUE TITLE
follow up from #237 & #239

### ISSUE THREAD

**Issue by mutricyl** [hgrecco/pint-pandas#240]
This is a follow up from pandas nightly build CI job introduction. The following tests have been skipped to get green light workflow for #239. They need to be fixed.

Looks like also that `unique` function was inducing errors in tests but this was unexpectedly solved. It might be worth to investigate this a little bit.

> skipped tests:
>
> - test_pandas_extensiontests.py::TestPintArray::test_arith_frame_with_scalar : tests with "__radd__", "__rsub__",  "__rmul__",  "__rtruediv__",          "__rpow__" are not working with pandas 3
> - test_issues.py::TestIssue80::test_div : pandas 3 is so fast that _timeit returns 0
> - test_pandas_extensiontests.py : all test including complex are skipped due to `NumpyExtensionArray` issue in pandas take function https://github.com/pandas-dev/pandas/issues/59177
> 
> all temporary skip are marked by `GH #239`

_Originally posted by @mutricyl in https://github.com/hgrecco/pint-pandas/issues/239#issuecomment-2208856625_
            
> Looks like there's a unique function issue similar to the take issue
> 
> pint_pandas/testsuite/test_pandas_extensiontests.py::TestPintArray::test_value_counts_with_normalize[float] - TypeError: unique requires a Series, Index, ExtensionArray, or np.ndarray, got NumpyExtensionArray. FAILED

_Originally posted by @andrewgsavage in https://github.com/hgrecco/pint-pandas/issues/239#issuecomment-2209347877_

**Comment by mutricyl** [comment]
https://github.com/pandas-dev/pandas/issues/59177 was resolved so `complex` may be allowed again for pandas >= 3

**Comment by mutricyl** [comment]
The two pandas issues with `take` and `unique` being solved, I add a look at the `r` operator issue in `test_pandas_extensiontests.py::TestPintArray::test_arith_frame_with_scalar`

I have identified the change in behavior is pandas 3 that induce pint and pint-pandas to fail with right operator. `pint.compat.is_upcast_type` behavior changed between pandas version due to `type(df)` that used to return `<class 'pandas.core.frame.DataFrame'>` which is now returning `<class 'pandas.DataFrame'>`.

@andrewgsavage do you think we should tackle this on the pandas side or on pint side ?

**Comment by andrewgsavage** [comment]
nice find, just need to add `pandas.DataFrame` to
https://github.com/hgrecco/pint/blob/b2fc74a7d6038d206d158804daa32e1698f89c26/pint/compat.py#L242

**Comment by mutricyl** [comment]
for the record the pandas' change is a features : https://github.com/pandas-dev/pandas/pull/55171

**Comment by mutricyl** [comment]
shall we make CI-pandas-pre use also pint pre version or update the tests to xfail while pint is not strictly above 0.24.1 ?

**Comment by andrewgsavage** [comment]
I'll release a new pint version after `pandas.DataFrame` and `pandas.Series` are added to upcast types
