### ISSUE TITLE
Typerror when calling numpy method on series containig pintarray

### ISSUE THREAD

**Issue by amine-aboufirass** [hgrecco/pint-pandas#25]
Do `PintArrays` support numpy operations? Take something like 
```
import pandas as pd
import pint
import numpy as np
ureg = pint.UnitRegistry()
pint.PintType.ureg = ureg

def f(x):
    return np.log(x/1*ureg.day)

df = pd.DataFrame({'A':pd.Series([1,2,3,4], dtype='pint[day]'),'B':pd.Series([5,6,7,8], dtype='pint[day]')})
f(df['A'])
```

I get an error:

`TypeError: loop of ufunc does not support argument 0 of type Quantity which has no callable log method`

Whereas:

`np.log10(1*ureg.day/(1*ureg.day))` 

Works.

**Comment by andrewgsavage** [comment]
it does now  after #160
