### ISSUE TITLE
Cannot check Dimensionality of DataFrame Cells (with Function Decorator)

### ISSUE THREAD

**Issue by michaelweinold** [hgrecco/pint-pandas#256]
Using [the dimensionality checking functionality](https://pint.readthedocs.io/en/stable/advanced/wrapping.html#checking-dimensionality) of pint does not work on elements of a PintArray taken from a DataFrame... unless I am missing something. Unfortunately, I could not find a workaround in the documentation or the repository issues.

Example:

We define a simple dataframe with two columns and associated units. We also define two quantities to see if we can check their dimensions:

```python
import pandas as pd
import pint_pandas
import pint
ureg = pint.UnitRegistry()

df = pd.DataFrame(
  {
      ('weight', 't'): [200]
  }
).pint.quantify(level=1)

weight = 200 * ureg.t
```

We can check the dimensionality of both the variable `weight` and an element of the `weight` column in the DataFrame:

```python
>>> weight_var.check('[mass]')
True
>>> df.iloc[0]['weight'].check('[mass]')
True
```

However, when using the `check` decorator on a simple function:

```python
@ureg.check(
    '[mass]',
)
def test_func(weight):
    return weight * 2

test_func(df.iloc[0]['weight'])
```

The dimensions cannot be checked, and instead we get an error
 
```
{
	"name": "DimensionalityError",
	"message": "Cannot convert from '200 metric_ton' ([mass]) to 'a quantity of' ([mass])",
	"stack": "---------------------------------------------------------------------------
DimensionalityError                       Traceback (most recent call last)
Cell In[42], line 7
      1 @ureg.check(
      2     '[mass]',
      3 )
      4 def test_func(weight):
      5     return weight * 2
----> 7 test_func(df.iloc[0]['weight'])

File /opt/homebrew/Caskroom/miniconda/base/envs/aircraft_performance/lib/python3.13/site-packages/pint/registry_helpers.py:381, in check.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    379     if not ureg.Quantity(value).check(dim):
    380         val_dim = ureg.get_dimensionality(value)
--> 381         raise DimensionalityError(value, \"a quantity of\", val_dim, dim)
    382 return func(*args, **kwargs)

DimensionalityError: Cannot convert from '200 metric_ton' ([mass]) to 'a quantity of' ([mass])"
}
```

**Comment by andrewgsavage** [comment]
Looks like you're using a different ureg to the application registry used
by pint.

try using
`ureg = pint.get_application_registry()`

**Comment by michaelweinold** [comment]
Ah, I see! I had not tried this, since this part of the API was listed under "Sharing registry among packages". I guess `pint_pandas` and `pint` also falls into that category. 
 
```python
import pandas as pd
import pint
import pint_pandas
ureg = pint.get_application_registry()

df = pd.DataFrame(
  {
      ('range', 'km'): [200]
  }
).pint.quantify(level=1)

df = df.pint.convert_object_dtype()

@ureg.check(
    '[length]',
)
def multiply_value(range):
    return range * 2

multiply_value(df.iloc[0]['range'])
```

works fine now. Thank you very much, @andrewgsavage! Should I open a PR on the documentation of `pint_pandas` to let other users know?

**Comment by andrewgsavage** [comment]
yes, please do
