### ISSUE TITLE
AttributeError: 'PintSeriesAccessor' object has no attribute '_index'

### ISSUE THREAD

**Issue by Artinix** [hgrecco/pint-pandas#260]
Hello, 

I have the following error occurring in Python 3.13 while using pint-pandas:

AttributeError: 'PintSeriesAccessor' object has no attribute '_index'

`data_selection[quantity_column] = data_selection[quantity_column].astype(f"pint[{unit_of_measure}]").pint.convert_object_dtype()
data_selection["activity_data_processed_quantity"] = data_selection["activity_data_processed_quantity"].pint.to("L").magnitude.round(10)`

Could you let me know how to fix it? It looks like mapping on core Pint package is done incorrect in pint-pandas

**Comment by andrewgsavage** [comment]
could you give code for a minimall reproducible example?

**Comment by Artinix** [comment]
Sorry, false alarm - my code tried to make calculations after the concatenation of two DataFrames, where each of them has a different unit assigned in dtype of "activity_data_processed_quantity". Issue closed
