### ISSUE TITLE
Support Pandas 1.0.0

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint-pandas#27]
Pandas has released version 1.0.0 Therefore we should be able to build against a stable API now.

**Comment by johnbomidi** [comment]
It’s not clear if the v25 comparability merge changes have happened ? https://github.com/hgrecco/pint-pandas/issues/20#issuecomment-536168950

@andrewgsavage @hgrecco 

I’d imagine that would be a step in this direction? What else needs to be done and how can people help?

**Comment by andrewgsavage** [comment]
Pandas 1.1.0 tests:
- [ ] 'BaseArithmeticOpsTests',
- [ ]  'BaseBooleanReduceTests',
- [ ]  'BaseCastingTests',
- [ ]  'BaseComparisonOpsTests',
- [ ]  'BaseConstructorsTests',
- [ ]  'BaseDtypeTests',
- [ ]  'BaseGetitemTests',
- [ ]  'BaseGroupbyTests',
- [ ]  'BaseInterfaceTests',
- [ ]  'BaseMethodsTests',
- [ ]  'BaseMissingTests',
- [ ]  'BaseNoReduceTests',
- [ ]  'BaseNumericReduceTests',
- [ ]  'BaseOpsUtil',
- [ ]  'BaseParsingTests',
- [ ]  'BasePrintingTests',
- [ ]  'BaseReshapingTests',
- [ ]  'BaseSetitemTests',
- [ ]  'BaseUnaryOpsTests',



<details>
  <summary>to recreate list</summary>
  
```
import pprint
from pandas.tests.extension import base

pprint.pprint(dir(base))
import pandas
print(pandas.__version__)
```
  
</details>
