### ISSUE TITLE
Update to pandas 1.0.4 prior to release

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint-pandas#33]
The current status for the tests (run in my computer) is:
- failed: 63
- passed: 265
- ignored: 2

**Comment by hgrecco** [comment]
Now
    failed: 62
    passed: 266
    ignored: 2

But not sure if all should pass or some are expected to fail

**Comment by znicholls** [comment]
@andrewgsavage i think you did most of the heavy lifting, any thoughts?

**Comment by hgrecco** [comment]
Update:

- failed: 51
- passed: 301
- ignored: 29

Things that re failing that I think should not:
- reverse binary ops (i.e. `radd`)
- compare ops

**Comment by hgrecco** [comment]
Update:
- failed: 36
- passed: 316
- ignored: 29

**Comment by hgrecco** [comment]
Update:

- failed: 23
- passed: 329
- ignored: 29

**Comment by andrewgsavage** [comment]
My last look at it was here.
https://github.com/hgrecco/pint-pandas/pull/29

I also had trouble with the TestMethods.test_where_series test
https://github.com/pandas-dev/pandas/issues/33825

**Comment by znicholls** [comment]
> #29

Looks nasty. @hgrecco how would you feel about xfailing the remaining tests and doing a 0.1.0dev release just to reserve the name on pypi and conda? Yes it's full of bugs, but I can't see a fast fix for #29 given you have to somehow remove the `__iter__` property on `Quantity` depending on whether magnitude is an array or not...

**Comment by hgrecco** [comment]
Update:

- failed: 21
- passed: 331
- ignored: 29

**Comment by hgrecco** [comment]
@znicholls I actually agree. Adoption will help to find and fix bugs. And 21 failing and 331 passing is not so bad for a 0.1

**Comment by hgrecco** [comment]
> somehow remove the __iter__ property on Quantity depending on whether magnitude is an array or not (or a ScalarQuantity class has to be distinguished from a ArrayQuantity class or something...)

This discussion is one of the reasons preventing me to release Pint 1.0. 

Looking at the the error in pint-pandas, I found that many of the problems arise form a wrong result in `is_list_like` (likely related to exactly what you mentioned). But `ndarray` does it right. 

```python
>>> import numpy as np
>>> x = np.zeros(3)
>>> y = np.asarray(3)
>>> type(x)
<class 'numpy.ndarray'>
>>> type(y)
<class 'numpy.ndarray'>
>>> x
array([0., 0., 0.])
>>> y
array(3)
>>> len(x)
3
>>> len(y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: len() of unsized object
>>> iter(x)
<iterator object at 0x7f8831837af0>
>>> iter(y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: iteration over a 0-d array
>>> from pandas._libs import lib
>>> lib.is_list_like(x)
True
>>> lib.is_list_like(y)
False
```

Can we copy from it?

**Comment by znicholls** [comment]
> Can we copy from it?

Here 'it' being ndarray?

**Comment by hgrecco** [comment]
Yes. I trying to look how it is done. It is weird because Quantity raises TypeError (like ndarray) upon calling `__iter__` or `__len__`

**Comment by hgrecco** [comment]
`is_list_like` is defined [here](https://github.com/pandas-dev/pandas/blob/4743cc91719146167eefb43865413fc0b0aef1d4/pandas/_libs/lib.pyx#L992)

```
    return (
        isinstance(obj, abc.Iterable)
        # we do not count strings/unicode/bytes as list-like
        and not isinstance(obj, (str, bytes))
        # exclude zero-dimensional numpy arrays, effectively scalars
        and not (util.is_array(obj) and obj.ndim == 0)
        # exclude sets if allow_sets is False
        and not (allow_sets is False and isinstance(obj, abc.Set))
    )
```

**Comment by znicholls** [comment]
> obj.ndim == 0

looks like that'll be the key

**Comment by znicholls** [comment]
> util.is_array(obj)

I think is_array is defined here https://github.com/pandas-dev/pandas/blob/f89ce8c079c43df99ff84ce8755fb8ea3915e30c/pandas/_libs/tslibs/util.pxd#L154 so a pint object will never hit it because it's not a numpy array. Hence the check `and not (util.is_array(obj) and obj.ndim == 0)` won't trigger...

**Comment by hgrecco** [comment]
That is indeed the case! Tomorrow I will make a release of pint-pandas and open and issue in Pint

**Comment by znicholls** [comment]
Hey @hgrecco, just wanted to see if that release ended up happening?

**Comment by hgrecco** [comment]
We release on friday no matter what, but this looks very promising: https://github.com/hgrecco/pint/pull/1125

**Comment by hgrecco** [comment]
I did it today as after several tries, I think that hgrecco/pint#1125 won't work
