### ISSUE TITLE
Can you make PintType.ureg settable?

### ISSUE THREAD

**Issue by zobac** [hgrecco/pint-pandas#37]
Would it make sense to have PintType.ureg use pint.get_application_registry() to allow using a common UnitRegistry?  In the past I have just done PintType.ureg = myUREG, but that gets overridden if pint_array gets imported elsewhere.  It would be great  to be able to guarantee that all PintTypes would (or could) use a common UnitRegistry.

**Comment by andrewgsavage** [comment]
yes, this caught me and I spent way too long debuging due to this...

**Comment by hgrecco** [comment]
I agree 100%
