### ISSUE TITLE
conda-forge install doesn't work

### ISSUE THREAD

**Issue by igurin-invn** [hgrecco/pint-pandas#41]
I see instructions on the project homepage to install from conda-forge. But the project isn't listed on the conda-forge website ([https://conda-forge.org/feedstocks/](url)), and copying the command string into my Anaconda prompt results in a PackagesNotFoundError.

**Comment by znicholls** [comment]
@hgrecco can I help with this one?

**Comment by znicholls** [comment]
As a quick check that things would behave I made https://github.com/conda-forge/staged-recipes/pull/12266. @hgrecco feel free to use/ignore/start a new PR as you see fit

**Comment by hgrecco** [comment]
ping @dopplershift. I think you are the right person for this job :-)

**Comment by dopplershift** [comment]
I think this is fixed now:
```
❯ conda search pint-pandas
Loading channels: done
# Name                       Version           Build  Channel             
pint-pandas                      0.1            py_0  conda-forge         
```

**Comment by igurin-invn** [comment]
The install works now, thanks!
