### ISSUE TITLE
pint pandas DataFrame throws exception on standard df methods like sum(), min() and max()

### ISSUE THREAD

**Issue by romor001** [hgrecco/pint-pandas#45]
### Description
When using pint enabled DataFrames, the well known methods of Pandas DataFrames like sum(), min() and max() are throwing an exception. Example:
`TypeError: cannot perform min with type pint[kilogram * meter]`

### Expected behaviour

Using standard DataFrame methods should work with pint enabled DataFrames, preserving the column units and returning a calculated value that has a pint unit attached to it.

### Steps to reproduce

Setting the pint_pandas unit registry to a ureg that can also be used outside the dataframes:
```
import pandas as pd
import pint
import pint_pandas
u = pint.UnitRegistry()
pint_pandas.PintType.ureg = u
```

Creating a Pint Pandas DataFrame as ususal:

```
PA_ = pint_pandas.PintArray

df = pd.DataFrame({
        "torque": PA_([1, 2, 2, 3], dtype=u.kg*u.m),
        })
```

Invoking a Pandas DataFrame method results in an exception:

```
df['torque'].min()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-488b600ceff2> in <module>
----> 1 df['torque'].min()

/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py in stat_func(self, axis, skipna, level, numeric_only, **kwargs)
  11463         if level is not None:
  11464             return self._agg_by_level(name, axis=axis, level=level, skipna=skipna)
> 11465         return self._reduce(
  11466             func, name=name, axis=axis, skipna=skipna, numeric_only=numeric_only
  11467         )
/usr/local/lib/python3.8/dist-packages/pandas/core/series.py in _reduce(self, op, name, axis, skipna, numeric_only, filter_type, **kwds)
   4225         if isinstance(delegate, ExtensionArray):
   4226             # dispatch to ExtensionArray interface
-> 4227             return delegate._reduce(name, skipna=skipna, **kwds)
   4228 
   4229         else:
/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/base.py in _reduce(self, name, skipna, **kwargs)
   1145         TypeError : subclass does not define reductions
   1146         """
-> 1147         raise TypeError(f"cannot perform {name} with type {self.dtype}")
   1148 
   1149     def __hash__(self):
TypeError: cannot perform min with type pint[kilogram * meter]
```

### Workaround

It is possible to remove the quantities before the operation and re-attaching them afterwards to the result value:
`df.pint.dequantify()['torque'].min()[0] * df.torque.pint.units`
But this is tedious.

Note: The workaround only works with columns that do not have spaces in the column name.

**Comment by andrewgsavage** [comment]
weird, I get 
```python3
type(df['torque'].min())

numpy.int32
```
which isn't ideal as it loses unit. What versions of pint/numpy are you using?

'numpy': '1.19.1',
 'pandas': '1.0.5',
 'pint': '0.16.1',
 'pint_pandas': '0.1.dev57+g5574c31.d20201010'

**Comment by romor001** [comment]
```
numpy                             1.18.5
pandas                            1.1.2
Pint                                  0.15
Pint-Pandas                       0.1
```

**Comment by andrewgsavage** [comment]
Prolly pandas or numpy version that's causing different behaviour. Need to check whether __array_function__ defaults to on in np 1.18.

It's interesting that min(Series) gives a pint quantity. Must be a different code path.
```
pa = PA_([1, 2, 2, 3], dtype=u.kg*u.m)
pa
<PintArray>
[1, 2, 2, 3]
Length: 4, dtype: pint[kilogram * meter]

min(pa)
1 kilogram meter

s=pd.Series(pa)
min(s)
1 kilogram meter

s.min()
1

```
