### ISSUE TITLE
Fixing the tests

### ISSUE THREAD

**Issue by znicholls** [hgrecco/pint-pandas#52]
I'd like to add a PR which fixes #51 but it's not possible at the moment because the tests wouldn't pass, even if I made the right change. More generally, at the moment we can't really do any meaningful pull request reviews because the tests are failing. 

@andrewgsavage I think you have the best overview of this, can you see a way to get the tests going again? For example, could we split #48 into two: 1. fix tests, 2. fix offset units? That would help things move and give a clearer sense of what functionality is still not yet implemented (because it's waiting on fixes to e.g. https://github.com/pandas-dev/pandas/issues/35131

**Comment by andrewgsavage** [comment]
I fixed the tests in #40 , then fixed offset units in #48 continuing from #40 .

@hgrecco attempted to merge #40 but there was an issue with bors. We're waiting on that to get tests going again.


It would be great to get tests going again, I wanted to see if plotting was possible in pandas 1.3 following https://github.com/pandas-dev/pandas/pull/38246 but also hit #51

**Comment by znicholls** [comment]
Awesome thanks for the update, I'll leave until #40 is merged

**Comment by znicholls** [comment]
Are the tests even running now? ping @hgrecco

**Comment by hgrecco** [comment]
Now. Travis changed a lot. We need to move this to GitHub actions as we did for pint.

**Comment by znicholls** [comment]
Ok thanks for the update. I can copy the pint setup at some point in the next few days.

**Comment by hgrecco** [comment]
Tests are running now (but not passing) on GitHub actions.
