### ISSUE TITLE
Shall we release a new version?

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint-pandas#54]
My idea is to release a new version by the end of the week
- Can we close any addition issue/PR by then?
- Shall we wait for any particular issue/PR?

**Comment by andrewgsavage** [comment]
I think you've merged the important ones. 

There's newer pandas versions but they may need additional tests so won't be done this week. 

Making the ureg settable is the next issue I'd like to work on https://github.com/hgrecco/pint-pandas/issues/37
as it'll make plotting in later versions slightly nicer https://github.com/hgrecco/pint-pandas/issues/9

**Comment by andrewgsavage** [comment]
Can we get a new version released? 

#37 will need a new version of pint released that doesn't import pint-pandas before it can be fixed
#9 requires newer compatibility with newer pandas versions which we now have.

**Comment by hgrecco** [comment]
Pint 0.17 is out! Shall we fix #37 and then do the release?

**Comment by andrewgsavage** [comment]
That's done, all set for a new version

**Comment by hgrecco** [comment]
I was about to change the requirements to
pint>=0.17
pandas>=1.2

What do you think?

**Comment by andrewgsavage** [comment]
Ah yes that'd be helpful

**Comment by hgrecco** [comment]
Done!. 0.2 released. Thanks for the great work!.
