### ISSUE TITLE
PintArray's `data_dtype` is ignored

### ISSUE THREAD

**Issue by a7p** [hgrecco/pint-pandas#57]
PintArray.__init__ ignores the `data_dtype` agument.

Something like this would fix it:
https://github.com/hgrecco/pint-pandas/pull/56

**Comment by andrewgsavage** [comment]
Yes that would fix it. 

For simplicity we decided to make pint pandas work with floats. All tests use floats so any other dtypes are untested. I think things will fall over when trying to use integers as np arrays of integers can't store nan. 

I think it's worth removing this argument and converting inputs to floats, with a warning to make this clearer.

Getting other dtypes to work would require changing the way the magnitude is stored and mean testing other dtypes so isn't easy.
