### ISSUE TITLE
Python versions to support

### ISSUE THREAD

**Issue by znicholls** [hgrecco/pint-pandas#6]
As it says in the title. I think the things we have to consider are:

- versions supported by Pint (many)
- versions support by Pandas (2.7, 3.5+) 
- each extra Python version we support makes things trickier

My preference would be to only support the same Python versions as Pandas, thoughts @hgrecco and @andrewgsavage?

**Comment by andrewgsavage** [comment]
Since that's the more limiting case I agree. There's no use supporting 3.3 if pandas does not .

We've not tested in anything other than 3.6 though, wonder if it works in 2.7/how much work it'd be to support it .

**Comment by hgrecco** [comment]
Sounds good to me.

**Comment by znicholls** [comment]
Sounds good

**Comment by znicholls** [comment]
From https://github.com/pandas-dev/pandas/releases

> Note that 0.24.x is the last series of releases to support Python 2.

I guess we drop Python 2 support then?

**Comment by andrewgsavage** [comment]
I think so, don't really want to deal with getting the tests to pass... https://travis-ci.com/andrewgsavage/pint-pandas/jobs/170678986

If someone else wants it in 2.7 they're welcome to do so and we could support until pandas 0.25.
