### ISSUE TITLE
Implement numpy __array_ufunc__

### ISSUE THREAD

**Issue by andrewgsavage** [hgrecco/pint-pandas#65]
Some numpy functions, like np.absolute applied to a Series containing a PintArray return a series with object dtype.

Implementing numpy's ```__array_ufunc__``` would allow functions like np.absolute to return a series containing a PintArray.

Current behaviour
```
import pint
import pandas as pd
import pint_pandas
pa = PA_([2,3.5], dtype="in")
s= pd.Series(pa)
np.absolute(s)

0    2 inch
1    3 inch
dtype: object
```
Desired behaviour 
```
import pint
import pandas as pd
import pint_pandas
pa = PA_([2,3.5], dtype="in")
s= pd.Series(pa)
np.absolute(s)

0    2
1    3
dtype: pint[inch]
```

**Comment by Nordicus** [comment]
As this issue still seems to be open, may I suggest for other users struggling with the same issue the following wrapper function:
```
def pt_pd_wrap(func, *data):
    a = [Q_(d.values._data, d.dtype.units) for d in data]
    res = func(*a)
    return pd.Series(pint_pandas.PintArray(res, dtype=res.units))
```
An example use case as above would therefore be:
```
pa = PA_([2,3.5], dtype="in")
s= pd.Series(pa)
pt_pd_wrap(np.absolute, s)
```
Which does in fact yield
```
0    2.0
1    3.5
dtype: pint[in]
```

**Comment by MichaelTiemannOSC** [comment]
The sample code needs to import numpy as np.
