### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by znicholls** [hgrecco/pint-pandas#7]
Related to #6, which of Pint's dependencies do we want to include? As it's simpler, I'd prefer to only support Pint with a full installation (i.e. make the latest numpy and uncertainties dependencies too) rather than support all the different combinations of numpy versions and other libraries (hence move away from the things are done in Pint).

**Comment by hgrecco** [comment]
I would like to make 'measurements' a independent package allowing it to move independently and taking with it the `uncertainties` dependency. 

Regarding numpy, I think we should just let pandas take care of that.

**Comment by znicholls** [comment]
Ok great sounds good
