### ISSUE TITLE
Display of decimal places

### ISSUE THREAD

**Issue by danolson1** [hgrecco/pint-pandas#74]
How do I control the number of decimal places that are displayed when Pint objects with float magnitudes are displayed in a Pandas DataFrame?

**Comment by dcoukos** [comment]
@danolson1 I think the function you are looking for is pandas.DataFrame.round. 

@hgrecco I actually wanted to open an issue about this. This function does not seem to work on data frames with dtype = pint units. 

In your case you might want to use `your_df.astype(float).round(decimals=your_decimals)`

**Comment by danolson1** [comment]
I don't want it to actually round the values. `df.style.format({'column_name': '{:.2f}'})` is a workaround, but it would be more convenient if there was a global option to set this for all pint data types.

**Comment by andrewgsavage** [comment]
You can use pint's string formatting options by setting the ureg's default format:
`pint_pandas.PintType.ureg.default_format = "~P"
`
https://pint.readthedocs.io/en/stable/tutorial.html#string-formatting

**Comment by danolson1** [comment]
Thanks. That's just what I was looking for.
