### ISSUE TITLE
Seems like this should work but UndefinedUnitError

### ISSUE THREAD

**Issue by dcoukos** [hgrecco/pint-pandas#79]
Following along with the documentation of pint-pandas and pint as best I could, I have an implementation which does not seem to want to work. This reproduces my UndefinedUnitError.

python: 3.8.8
pint: 0.17
pint-pandas: 0.2

```
import pint
import pint_pandas
ureg = UnitRegistry()
ureg.load_definitions('pint_unit_definitions.txt')
pint.set_application_registry(ureg)


df = pd.DataFrame([[4,5,6],[1,3,4]], dtype='pint[bpm]' )
```

My pint_unit_definitions.txt file looks like this:

```
minute = 60 * second = min
beats_per_minute = beat / minute = bpm
hertz = counts / second = hz
beat = [heart_beats] = b
```

Am I doing something wrong? Thanks!

**Comment by andrewgsavage** [comment]
Add  `pint_pandas.PintType.ureg = ureg` after you set the application registry

**Comment by dcoukos** [comment]
Thanks!
