### ISSUE TITLE
Pint creating a second registry

### ISSUE THREAD

**Issue by jennifer-dicarlo** [hgrecco/pint-pandas#81]
Hi.  I don't know if this is an issue/bug....but the following code is giving inconsistent registry results....

If I run it after a kernel restart, Pint only creates one registry.  The output looks something like:

```
Constants Dictionary Unit Registries
g:  140391382456736
cdg:  140391382456736
Fluid Dictionary Unit Registries
fdex:  140391382456736
DataFrame Unit Registries
ID:  140391382456736
V:  140391382456736
```

If I run the code again, the registries for the last two quantities stay the same, but new registries are created for the first three quantities....

```
Constants Dictionary Unit Registries
g:  140391416170096
cdg:  140391416170096
Fluid Dictionary Unit Registries
fdex:  140391416170096
DataFrame Unit Registries
ID:  140391382456736
V:  140391382456736`
```

Clearing the variables doesn't have any effect.  

```
Constants Dictionary Unit Registries
g:  140391416999456
cdg:  140391416999456
Fluid Dictionary Unit Registries
fdex:  140391416999456
DataFrame Unit Registries
ID:  140391382456736
V:  140391382456736`
```

The only way I get back to one registry is to restart the kernel.

It's probably just something I'm doing wrong....but I've searched all the help/examples I can find and haven't stumbled upon something to explain it.

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import print_function, absolute_import, division
import pandas as pd
import pint # Units
import pint_pandas as ppi

# Unit Registry
ureg = pint.UnitRegistry(auto_reduce_dimensions=False)
pint.set_application_registry(ureg)
ppi.PintType.ureg = ureg
ppi.PintType.ureg.default_format = "~P"

# Constants and Parameters
#Acceleration Due to Gravity
g = 1.0 * ureg.g_0
g.ito(ureg.foot / ureg.second**2 ) # ft/s2

print('Constants Dictionary Unit Registries')
print('g: ', id(g._REGISTRY))

# Constants Dict
const_dict = {}
const_dict['g'] = g
const_dict['SL_LB'] = 1.0*ureg.slug/(1.0*ureg.slug).to(ureg.pound) # slug/lb
const_dict['rho'] = 68.48 * ureg.pound / ureg.foot**3  #lbMass/ft^3
const_dict['eta'] = 0.6644 * ureg.centipoise

# Check registry of constants dictionary
cdg = const_dict['g']
print('cdg: ', id(cdg._REGISTRY))

# Fluid Dict
fluid_dict = {}
fluid_dict['Dens_SL'] = const_dict['rho'] * const_dict['SL_LB'] # slugs/ft3
fluid_dict['DynVisc_LBFT2'] = const_dict['eta'].to(ureg.force_pound * ureg.second / ureg.foot**2) #lbF-s/ft2

# Check registry of fluid dictionary
fdex = fluid_dict['Dens_SL']
print('Fluid Dictionary Unit Registries')
print('fdex: ', id(fdex._REGISTRY))

# Small segment of the input data
Dij = [4.0]*4
Lij = [2000.0]*4
data = {'Dij': Dij, 'Lij': Lij}
arc = pd.DataFrame(data=data)

# Put Data into DataFrame
df = pd.DataFrame({
        "Dij": ppi.PintArray(arc['Dij'], dtype=ureg.inch),
        "Lij": ppi.PintArray(arc['Lij'], dtype=ureg.foot)
    }, index=arc.index)

print('DataFrame Unit Registries')
ID = df.at[0,'Dij']
print('ID: ', id(ID._REGISTRY))

v = list(range(1,3))
vels = ppi.PintArray(v, dtype=ureg.foot/ureg.second)

# Check registry of Pint Array content
vt=vels[0]
print('V: ', id(vt._REGISTRY))

vvels = [vels]*len(arc)
vv = list(zip(arc.index.values, vvels))
vd = dict(vv)
pwdf = pd.DataFrame(vd, index=v)
pwdf2 = pwdf.T

# Breaks here....
#for y in vels:
#    ReNumb = y * ID * fluid_dict['Dens_SL'] / fluid_dict['DynVisc_LBFT2']
#    ReNumb.ito_reduced_units()
#    print(ReNumb)
```

**Comment by andrewgsavage** [comment]
I'm assuming you're using jupyter since you mentioned kernels. I think you should avoid rerunning the imports and recreating a ureg each time. In the background pint-pandas registers its extension dtype with pandas on import, so I'm not sure how that will work when reimporting it. Does it work if you run all, then run from 'Constants and Parameters' onwards?

There's a lot here, more than is necessary to understand the problem. In future please try to reduce your problem to as few lines as possible while still showing the issue, and use the code formatting in github so it can be copy pasted, eg
\``` your code here```

**Comment by jennifer-dicarlo** [comment]
Thanks for getting back to me.

I actually use Spyder. I tried Jupyter in a desperate attempt to find a way that worked…I thought maybe it could be a version issue.  Both Spyder and Jupyter I need to restart the kernel or the program (which restarts the kernel).  Just clearing the variables in Spyder doesn’t fix it.

Yeah, the code got lengthy when I added the print statements.  But the print statements are the only way to show that there are two registries (at least that I know of).   Would you like me to take the print statements out?

I tried to cut the code down to just the quantities I needed to calculate the first value where it fails.  I wondered if the dictionary vs data frame had anything to do with it but that wouldn’t make any sense. The data frame registry doesn’t change no matter how many times I run it. The dictionary registry is the one that is different each run. Does that make any sense?

I’m not home right now but later today I can try running the second part of the code without the first. I do Operations Research so I am not a “comp sci” person. I know enough coding to do the processing my models need but it’s usually inefficient…I never thought about putting the imports in just one place…

In the actual program I was doing some of the calculations in a main file and referencing the file with the ureg.  I had to add the prefix in the main program so that I didn’t get two registries.

Import hydro as hy

Then use hy.ureg…

The code I posted is all in one function because I thought that the second file was the issue (it wasn’t).

Yup, I ran out of things to try. :-)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hgrecco** [comment]
As @andrewgsavage do not run the code to instantiate the registry twice. If, for what ever reason, you can control which code you execute use `get_application_registry`. This will create a registry and then provide the same 

```python
>>> import pint
>>> ureg1 = pint.get_application_registry()
>>> ureg2 = pint.get_application_registry()
>>> ureg1 is ureg2
True
```

**Comment by jennifer-dicarlo** [comment]
I changed "set" to "get" in my example and now it works.  Strange though....why can't you tell it that the registry you just instantiated is the registry to use via "set"?

This is the example from the documentation:
```
from pint import UnitRegistry, set_application_registry
ureg = UnitRegistry()
set_application_registry(ureg)```

But that code doesn't work for me.  I had to change that "set" to "get" in order to get the same result as the above code should supply....

**Comment by hgrecco** [comment]
> why can't you tell it that the registry you just instantiated is the registry to use via "set"?
You can. But if you call that line again, you set the application registry again (and because you have instantiated another you are changing it)

If you call `get_application_registry` and no registry has been set, a new is created.

**Comment by andrewgsavage** [comment]
seems this is resolved
