### ISSUE TITLE
Documentation page doesn't render correctly, shows source code of Jupyter notebook

### ISSUE THREAD

**Issue by gerritholl** [hgrecco/pint-pandas#84]
Browsing to https://pint.readthedocs.io/en/stable/pint-pandas.html with Firefox 89 shows the following:

![image](https://user-images.githubusercontent.com/500246/124601574-49bcb100-de68-11eb-9988-464c76b1d8f8.png)

Instead of showing the marked up content, it appears to show the source code of a Jupyter notebook.

**Comment by andrewgsavage** [comment]
fixed with https://github.com/hgrecco/pint/pull/1318
