### ISSUE TITLE
`sqrt` doesn't work on PintArrays

### ISSUE THREAD

**Issue by burnpanck** [hgrecco/pint-pandas#85]
The following code fails in the last line:
```python
import numpy as np
import pandas as pa
import pint_pandas

x = pint_pandas.PintArray(np.arange(4),"m")
print(np.sqrt(x.quantity))
print(np.sqrt(x))
```

**Comment by burnpanck** [comment]
This is probably a duplicate of #65.

**Comment by andrewgsavage** [comment]
sqrt isn't affected by `__array_ufunc__` https://numpy.org/doc/1.14/neps/ufunc-overrides.html#list-of-operators-and-numpy-ufuncs

I think implementing `__array_function__` would fix sqrt and many other np functions. It'd affect PintArray but not Series

**Comment by burnpanck** [comment]
Thanks for the clarification! I didn't pay attention to the distinction of the two. So maybe I should edit this issue to make it ask for `__array_function__`?

**Comment by andrewgsavage** [comment]
well the code in OP works now, as of #160
