### ISSUE TITLE
`PintArray` should accept Quantity arrays directly

### ISSUE THREAD

**Issue by burnpanck** [hgrecco/pint-pandas#88]
Given a Quantity array `q`, the correct way to create a `PintArrray` currently is to call `PintArray(q.magnitude, q.units)`.
One may be tempted to instead call `PintArray(q, q.units)` instead, which gives the correct result, but causes a `UnitsStrippedWarning` to be raised. Either way, it would be much more convenient to simply call `PintArray(q)`.

Furthermore, one may instead expect `PintArray(q, some_unit)` to do the right thing(TM) (convert to `some_unit` if possible, otherwise fail loudly) - however, the units are just silently being replaced.

**Comment by danieldjewell** [comment]
Relatedly, accepting/interpreting lists/dicts of Quantities in the `DataFrame` constructor methods (namely `pandas.DataFrame.from_dict()` and `pandas.DataFrame.from_records()`) would also be awesome. 

e.g. given a `list[dict]` where each list entry is a row and the dict keys are columns:

```
inlist = [
{ 'power': 8*ureg.W }, 
{ 'power': 16*ureg.W}
]
```

It would be great if `df = pd.DataFrame.from_records(inlist)` would make the 'power' column of type `pint[Watt]` instead of the current `object`

**Comment by andrewgsavage** [comment]
Yes, this makes sense. Next on the to do list. Good spot on the unit conversion bug.

**Comment by andrewgsavage** [comment]
> Relatedly, accepting/interpreting lists/dicts of Quantities in the `DataFrame` constructor methods (namely `pandas.DataFrame.from_dict()` and `pandas.DataFrame.from_records()`) would also be awesome.
> 
> e.g. given a `list[dict]` where each list entry is a row and the dict keys are columns:
> 
> ```
> inlist = [
> { 'power': 8*ureg.W }, 
> { 'power': 16*ureg.W}
> ]
> ```
> 
> It would be great if `df = pd.DataFrame.from_records(inlist)` would make the 'power' column of type `pint[Watt]` instead of the current `object`

Not something pint-pandas has control over, you'd need to make a request to pandas.

`pd.DataFrame.from_records` accepts a dtype argument so you could do `dtype = 'pint[W]' `

**Comment by MichaelTiemannOSC** [comment]
I'd guess that the place to start with Pandas would be pandas.DataFrame.convert_dtypes (and in particular to make Quantities one of the fundamental things that Pandas respects, like ints, floats, strings, and booleans).  They offer the following invitation:

```
In the future, as new dtypes are added that support pd.NA, the results of this method will change to support those new dtypes.
```
