### ISSUE TITLE
floordiv with scalar is not working

### ISSUE THREAD

**Issue by carlculator** [hgrecco/pint-pandas#95]
I get an error when using the floordiv method on a `PintArray` with a scalar, see example below:

```python
from pint_pandas import PintArray
import pandas as pd

p = PintArray([1., 2.], dtype="m")
s = pd.Series(p)

s / 2  # works
s // 2  # pint.errors.DimensionalityError: Cannot convert from 'meter' to 'dimensionless'
```
 floordiv with another `PintArray` is working

software versions:
* python 3.7.10
* pandas 1.3.2
* pint 0.17
* pint_pandas 0.2

**Comment by andrewgsavage** [comment]
I think this is a pint issue, not a pint-pandas one
```
Q_([1., 2.], 'm') / 2 # works
Q_([1., 2.], 'm') //  2 # DimensionalityError: Cannot convert from 'meter' to 'dimensionless'
```

**Comment by carlculator** [comment]
For the sake of documentation, we may leave this issue open until https://github.com/hgrecco/pint/issues/943 is done.

**Comment by andrewgsavage** [comment]
can this be closed?
