### ISSUE TITLE
how to save units when writing to csv?

### ISSUE THREAD

**Issue by matthiasdebernardini** [hgrecco/pint-pandas#98]
I want to store a df with pint arrays, how do I store the pint type in csv?

Otherwise I have to readd it when I read it in.

**Comment by andrewgsavage** [comment]
https://pint.readthedocs.io/en/stable/pint-pandas.html#Reading-from-csv

'df_.pint.to_base_units().pint.dequantify()' gets you to a DataFrame you can write to a csv, then read back in
